exercisesproject/exercisesapp/urls.py
from django.urls import include, path
from .views import *

app_name = "exercisesapp"

urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_user, name='logout'),
    path('instructors/', instructor_list, name="instructors"),
    path('instructors/<int:instructor_id>/edit/', instructor_edit_form, name="instructor_edit_form"),
    path('instructors/<int:instructor_id>/', instructor_details, name="instructor"),
    path('students/', student_list, name="students"),
    path('students/<int:student_id>/', student_details, name="student"),
    path('students/new/', student_form, name="student_form"),
    path('students/<int:student_id>/edit/', student_edit_form, name="student_edit_form"),
    path('exercises/', exercise_list, name="exercises"),
    path('exercises/<int:exercise_id>/', exercise_details, name="exercise"),
    path('exercises/new/', exercise_form, name="exercise_form"),
    path('exercises/<int:exercise_id>/edit/', exercise_edit_form, name="exercise_edit_form"),
    path('cohorts/', cohort_list, name="cohorts"),
    path('cohorts/<int:cohort_id>/', cohort_details, name="cohort"),
    path('cohorts/new/', cohort_form, name="cohort_form"),
    path('cohorts/<int:cohort_id>/edit/', cohort_edit_form, name="cohort_edit_form"),
    path('exercises/<int:exercise_id>/assign', assignment_form, name="assignment_form"),
    path('exercises/<int:exercise_id>/assign/<int:assignment_id>', delete_assignment, name="delete_assignment"),

]

exercisesproject/exercisesproject/urls.py
from django.contrib import admin
from django.urls import include, path
from exercisesapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exercisesapp.urls'))
]

exercisesproject/exercisesapp/models/assignment.py
from django.db import models
from .exercise import Exercise
from .instructor import Instructor
from .student import Student

class Assignment(models.Model):

    exercise = models.ForeignKey("Exercise", on_delete=models.CASCADE)
    instructor = models.ForeignKey("Instructor", on_delete=models.CASCADE)
    student = models.ForeignKey("Student", on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("assignment")
        verbose_name_plural = ("assignments")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("assignment_detail", kwargs={"pk": self.pk})

exercisesproject/exercisesapp/models/cohort.py
from django.db import models

class Cohort(models.Model):

    name = models.CharField(max_length=50)
    

    class Meta:
        verbose_name = ("cohort")
        verbose_name_plural = ("cohorts")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("cohort_detail", kwargs={"pk": self.pk})

exercisesproject/exercisesapp/models/exercise.py
from django.db import models

class Exercise(models.Model):

    name = models.CharField(max_length=50)
    language = models.CharField(max_length=50)
    

    class Meta:
        verbose_name = ("exercise")
        verbose_name_plural = ("exercises")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("exercise_detail", kwargs={"pk": self.pk})

exercisesproject/exercisesapp/models/instructor.py
from django.db import models
from .cohort import Cohort
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Instructor(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slack_handle = models.CharField(max_length=50, null=True)
    specialty = models.CharField(max_length=50, null=True)
    cohort = models.ForeignKey(Cohort, null=True, blank=True,on_delete=models.CASCADE)


    @receiver(post_save, sender=User)
    def create_instructor(sender, instance, created, **kwargs):
        if created:
            Instructor.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_instructor(sender, instance, **kwargs):
        instance.instructor.save()

exercisesproject/exercisesapp/models/modelfactory.py
import sqlite3


def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

exercisesproject/exercisesapp/models/student.py
from django.db import models
from .cohort import Cohort

class Student(models.Model):

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    slack_handle = models.CharField(max_length=50)
    cohort = models.ForeignKey(Cohort, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Student")
        verbose_name_plural = ("Students")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Student_detail", kwargs={"pk": self.pk})

exercisesproject/exercisesapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

exercisesproject/exercisesapp/templates/cohorts/details.html
{% extends 'shared/base.html' %}

{% block content %}
<section id="cohort-details">
    <h2>{{cohort.name}}</h2>
</section>
<section id="cohort-actions">
    <form action="{% url 'exercisesapp:cohort_edit_form' cohort.id %}" method="GET">
        {%csrf_token%}
        <button>Edit</button>
    </form>

</section>
<section id="cohort-instructors">
    <h4>Instructors:</h4>
    <ul>
        {% for instructor in cohort.instructors %}
        <li><a href="{% url 'exercisesapp:instructor' instructor.id %}">{{instructor.first_name}} {{instructor.last_name}}</a></li>
        {% endfor %}
    </ul>
</section>
<section id="cohort-students">
    <h4>Students:</h4>
    <ul>
        {% for student in cohort.students %}
        <li><a href="{% url 'exercisesapp:student' student.id %}">{{student.first_name}} {{student.last_name}}</a></li>
        {% endfor %}
    </ul>
</section>

{% endblock %}

exercisesproject/exercisesapp/templates/cohorts/form.html
{% extends 'shared/base.html' %}

{% block content %}
{% if cohort.id is not None%}
<h2>Update Cohort Name</h2>
<form action="{% url 'exercisesapp:cohort' cohort.id %}" method="POST">
    {% else %}
    <h2>New Cohort</h2>
    <form action="{% url 'exercisesapp:cohorts' %}" method="POST">
    {% endif %}
    {% csrf_token %}
    <fieldset>
        <label for="name">Name: </label>
        <input required id="name" type="text" name="name" value="{{ cohort.name }}">
    </fieldset>

    {% if cohort.id is not None %}
    <input type="hidden" name="actual_method" value="PUT">
    {% endif %}

    <input type="submit" value="Submit" />
</form>
{% endblock %}

exercisesproject/exercisesapp/templates/cohorts/list.html
{% extends 'shared/base.html' %}

{% block content %}
<h2>Cohorts</h2>
<a href="{% url 'exercisesapp:cohort_form' %}">New Cohort</a>


<ul class="content_list">
    {% for cohort in all_cohorts %}
    <li class="content_list_item">
        <a href="{% url 'exercisesapp:cohort' cohort.id %}">{{cohort.name}}</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

exercisesproject/exercisesapp/templates/exercises/assignment_form.html
{% extends 'shared/base.html' %}

{% block content %}
<h2>Assign {{exercise.name}}</h2>
<p>The following students in your cohort have not been assigned {{exercise.name}}.</p>
<form action="{% url 'exercisesapp:exercise' exercise.id %}" method="POST">
    {% csrf_token %}
    <fieldset>
        <label for="student">Student: </label>
        <select required id="student" type="text" name="student">
            <option value="">--Select Student--</option>
            {% for student in all_students %}
            <option value="{{ student.id }}">
                {{ student.first_name }} {{ student.last_name }}
            </option>
            {% endfor %}
        </select>
    </fieldset>

    <!-- include hidden input to indicate that a different resource is being targeted -->
    <input type="hidden" name="actual_resource" value="assignment">

    <input type="submit" value="Submit" />
</form>


{% endblock %}

exercisesproject/exercisesapp/templates/exercises/details.html
{% extends 'shared/base.html' %}

{% block content %}
<section id="exercise-details">
    <h2>{{exercise.name}}</h2>
    <h3>{{exercise.language}}</h3>
</section>
<section id="exercise-actions">
    <form action="{% url 'exercisesapp:exercise_edit_form' exercise.id %}" method="GET">
        {%csrf_token%}
        <button>Edit</button>
    </form>
    <form action="{% url 'exercisesapp:exercise' exercise.id %}" method="POST">
        {%csrf_token%}
        <input type="hidden" name="actual_method" value="DELETE">
        <button>Delete</button>
    </form>
</section>
<section id="exercise-assignments">
    <h4>Assigned to:</h4>
    <form action="{% url 'exercisesapp:assignment_form' exercise.id %}" method="GET">
        {%csrf_token%}
        <button>Assign to Student</button>
    </form>
    <ul>
        {% for assignment in exercise.assignments %}
        <li>{{assignment.student.first_name}} {{assignment.student.last_name}} (assigned by {{assignment.instructor.first_name}} {{assignment.instructor.last_name}})
            {% if user.instructor.id == assignment.instructor.id %}
            <form action="{% url 'exercisesapp:delete_assignment' exercise.id assignment.id %}" method="POST">
                {%csrf_token%}
                <!-- include hidden input to indicate that a different resource is being targeted -->
                <input type="hidden" name="actual_resource" value="assignment"> 
                <input type="hidden" name="actual_method" value="DELETE">
                <button>Delete Assignment</button>
            </form>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</section>

{% endblock %}

exercisesproject/exercisesapp/templates/exercises/form.html
{% extends 'shared/base.html' %}

{% block content %}
<h2>Exercise Form</h2>
{% if exercise.id is not None%}
<form action="{% url 'exercisesapp:exercise' exercise.id %}" method="POST">
    {% else %}
    <form action="{% url 'exercisesapp:exercises' %}" method="POST">
    {% endif %}
    {% csrf_token %}
    <fieldset>
        <label for="name">Name: </label>
        <input required id="name" type="text" name="name" value="{{ exercise.name }}">
    </fieldset>
    <fieldset>
        <label for="language">Language: </label>
        <input required id="language" type="text" name="language" value="{{ exercise.language }}">
    </fieldset>

    {% if exercise.id is not None %}
    <input type="hidden" name="actual_method" value="PUT">
    {% endif %}

    <input type="submit" value="Submit" />
</form>
{% endblock %}

exercisesproject/exercisesapp/templates/exercises/list.html
{% extends 'shared/base.html' %}

{% block content %}
<h2>Exercises</h2>
<a href="{% url 'exercisesapp:exercise_form' %}">New Exercise</a>


    {% for group in all_exercises %}
    <h4>{{group.language}}</h4>
    <ul class="content_list">
        {% for exercise in group.exercise_list %}
        <li class="content_list_item">
            <a href="{% url 'exercisesapp:exercise' exercise.id %}">{{exercise.name}}</a>
        </li>
        {% endfor %}
    </ul>
    {% endfor %}
{% endblock %}

exercisesproject/exercisesapp/templates/home.html
{% extends 'shared/base.html' %}

{% block content%}
<h2>Welcome to the home page</h2>
{% endblock%}

exercisesproject/exercisesapp/templates/instructors/details.html
{% extends 'shared/base.html' %}

{% block content%}
<section id="instructor-details">
    <h2>{{instructor.first_name}} {{instructor.last_name}}</h2>
    <h3>Currently instructing: <a href="{% url 'exercisesapp:cohort' instructor.cohort.id %}">{{instructor.cohort.name}}</a></h3>
    <p>Slack Handle: {{instructor.slack_handle}}</p>
    <p>Specialty: {{instructor.specialty}}</p>
</section>
<section id="instructor-actions">
    <form action="{% url 'exercisesapp:instructor_edit_form' instructor.id %}" method="GET">
        {%csrf_token%}
        <button>Edit</button>
    </form>
</section>



{% endblock%}

exercisesproject/exercisesapp/templates/instructors/form.html
{% extends 'shared/base.html' %}

{% block content %}
<h2>Update Instructor Info</h2>
{% if instructor.id is not None %}
    <form action="{% url 'exercisesapp:instructor' instructor.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <label for="first_name">First Name: </label>
            <input required id="first_name" type="text" name="first_name" value="{{ instructor.first_name }}">
        </fieldset>
        <fieldset>
            <label for="last_name">Last Name: </label>
            <input required id="last_name" type="text" name="last_name" value="{{ instructor.last_name }}">
        </fieldset>
        <fieldset>
            <label for="cohort">Cohort: </label>
            <select required id="cohort" type="text" name="cohort">
                <option value="">--Select Cohort--</option>
                {% for cohort in all_cohorts %}
                <option {% if cohort.id == instructor.cohort_id %}selected{% endif %} value="{{ cohort.id }}">
                    {{ cohort.name }}</option>
                {% endfor %}
            </select>
        </fieldset>
        <fieldset>
            <label for="slack_handle">Slack Handle: </label>     
            <input required id="slack_handle" type="text" name="slack_handle" {%if instructor.slack_handle is not None %} value="{{ instructor.slack_handle }}"{% endif %}>

        </fieldset>
        <fieldset>
            <label for="specialty">Specialty: </label>
            <input required id="specialty" type="text" name="specialty" {%if instructor.specialty is not None %} value="{{ instructor.specialty }}" {% endif %}>
        </fieldset>
        <input type="hidden" name="actual_method" value="PUT">
        <input type="submit" value="Update" />
    </form>
    <section>
        <a href="{% url 'exercisesapp:instructor' instructor.id %}">Cancel</a>
    </section>

{% endif %}
{% endblock %}

exercisesproject/exercisesapp/templates/instructors/list.html
{% extends 'shared/base.html'%}

{% block content %}
<h2>List of Instructors</h2>

<ul class="content_list">
    {%for i in all_instructors%}
        <li class="content_list_item"><a href="{% url 'exercisesapp:instructor' i.id %}">{{i.first_name}} {{i.last_name}} </a></li>
        
    {%endfor%}
</ul>
{% endblock%}

exercisesproject/exercisesapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exercises</title>
    <link rel="stylesheet" href="{% static 'styles/base.css' %}">
    {% block css %}
    {% endblock css%}
</head>

<body>
    <nav id="site-nav">
        <ul class="navList">
            <li class="navList__route"><a href="{% url 'exercisesapp:cohorts' %}">Cohorts</a></li>
            <li class="navList__route"><a href="{% url 'exercisesapp:instructors' %}">Instructors</a></li>
            <li class="navList__route"><a href="{% url 'exercisesapp:students' %}">Students</a></li>
            <li class="navList__route"><a href="{% url 'exercisesapp:exercises' %}">Exercises</a></li>
            <div class="navList__user">
                {% if request.user.is_authenticated %}
                <li class="navList__route">Welcome {{request.user.first_name}}!</li>
                <li class="navList__route"><a href="{% url 'exercisesapp:logout' %}">Logout</a></li>
                {% else %}
                <li class="navList__route"><a href="{% url 'exercisesapp:login' %}">Login</a></li>
                {% endif%}
            </div>
        </ul>
    </nav>
    <main class="main-content">
        {% block content %}
        {% endblock content%}
    </main>
    {% block scripts %}
    {% endblock scripts%}
</body>

</html>

exercisesproject/exercisesapp/templates/students/details.html
{% extends 'shared/base.html' %}

{% block content %}
<section id="student-details">
    <h2>{{student.first_name}} {{student.last_name}}</h2>
    <h3>{{student.cohort.name}}</h3>
    <p>Slack Handle: {{student.slack_handle}}</p>
</section>
<section id="student-exercises">
    <h4>Assignments:</h4>
    <ul>
        {% for exercise in student.exercises %}
        <li>{{exercise.name}} ({{exercise.language}})</li>
        {% endfor %}
    </ul>
</section>
<section id="student-actions">
    <form action="{% url 'exercisesapp:student_edit_form' student.id %}" method="GET">
        {%csrf_token%}
        <button>Edit</button>
    </form>
    <form action="{% url 'exercisesapp:student' student.id %}" method="POST">
        {%csrf_token%}
        <input type="hidden" name="actual_method" value="DELETE">
        <button>Delete</button>
    </form>
</section>
{% endblock %}

exercisesproject/exercisesapp/templates/students/form.html
{% extends 'shared/base.html' %}

{% block content %}
<h2>Student Form</h2>


{% if student.id is not None %}
<form action="{% url 'exercisesapp:student' student.id %}" method="POST">
    {% else%}
    <form action="{% url 'exercisesapp:students' %}" method="POST">
        {% endif %}
        {% csrf_token %}
        <fieldset>
            <label for="first_name">First Name: </label>
            <input required id="first_name" type="text" name="first_name" value="{{ student.first_name }}">
        </fieldset>
        <fieldset>
            <label for="last_name">Last Name: </label>
            <input required id="last_name" type="text" name="last_name" value="{{ student.last_name }}">
        </fieldset>
        <fieldset>
            <label for="cohort">Cohort: </label>
            <select required id="cohort" type="text" name="cohort">
                <option value="">--Select Cohort--</option>
                {% for cohort in all_cohorts %}
                <option {% if cohort.id == student.cohort_id %}selected{% endif %} value="{{ cohort.id }}">
                    {{ cohort.name }}</option>
                {% endfor %}
            </select>
        </fieldset>
        <fieldset>
            <label for="slack_handle">Slack Handle: </label>
            <input required id="slack_handle" type="text" name="slack_handle" value="{{ student.slack_handle }}">
        </fieldset>

        {% if student.id is not None %}
        <input type="hidden" name="actual_method" value="PUT">
        {% endif %}

        <input type="submit" value="Submit" />
    </form>
    <section>
        {% if student.id is not None %}
        <a href="{% url 'exercisesapp:student' student.id %}">Cancel</a>
        {% else %}
        <a href="{% url 'exercisesapp:students' %}">Cancel</a>
        {% endif%}
    </section>

    {% endblock %}

exercisesproject/exercisesapp/templates/students/list.html
{% extends 'shared/base.html' %}

{% block content %}
<h2>List of Students</h2>

<a href="{% url 'exercisesapp:student_form' %}">New Student</a>

<ul class="content_list">
    {% for s in all_students %}
    <li class="content_list_item"><a href="{% url 'exercisesapp:student' s.id %}">{{s.first_name}} {{s.last_name}} </a></li>
    {% endfor %}
</ul>
{% endblock %}